# Site settings
name: My Little Diary
email: zhongyp001@163.com
author: zhongyp
url: http://www.zhongyp.me
resume_site: http://zhongyp.me
github: https://github.com/camda/
baseurl: ""
description: 忙活，或者等死。
meta_description: zhongyp;笔记•随笔;若你真的想做某事，你得努力上进、善用机会，而最重要的是决不放弃。
motto: shoot at the plane.
banner: 年轻的好处在于，你还没有太多经验，并天生相信一切皆可能。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: camda
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: c3a96bcff9ce4fd81c073bd0facf8a2a

