# site settings
name: Enjoy Life
email: zhongyp001@163.com
author: zhongyp
url: http://www.zhongyp.me
resume_site: http://zhongyp.me/about/
github: https://github.com/zhongyp/
baseurl: "http://zhongyp.me"
keywords: 钟宇鹏,笔记,随笔,zhongyp,个人博客,钟宇鹏的博客,个人网站,程序猿
description: 互联网世界的工程师,理性与感性,钟宇鹏的博客,

motto: 《回忆》
banner: 年轻的好处在于，你还没有太多经验，并天生相信一切皆可能。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: zhongyp
#highlighter: Pygments
highlighter: rouge

# baidu analytics
markdown: kramdown
baidu_analysis: c3a96bcff9ce4fd81c073bd0facf8a2a

# google analytics

ga_id: 'UA-104421653-1'
ga_domain: zhongyp.me
