# site settings
name: 狂人日记
email: zhongyp001@163.com
author: zhongyp
url: http://www.zhongyp.me
resume_site: http://zhongyp.me/me/
github: https://github.com/zhongyp/
baseurl: ""
keywords: "狂人日记,Java,钟宇鹏,笔记,随笔,zhongyp,个人博客,钟宇鹏的博客,个人网站,程序猿,Java工程师"
description: "对于你走完的路感到骄傲，对于你可以走多远感到自信，但不要忘记享受旅程。-- 一个在路上的Java工程师"
SEOTitle: "钟宇鹏的博客"


#banner_words
topic: ""
bio: "" 
post_ana: "年轻的好处在于，你还没有太多经验，并天生相信一切皆可能。"


#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

# filter
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

## social milieu
github_username: zhongyp

#highlighter: Pygments
highlighter: rouge

# baidu analytics
markdown: kramdown
baidu_analysis: c3a96bcff9ce4fd81c073bd0facf8a2a

# google analytics
ga_id: 'UA-104421653-1'
ga_domain: zhongyp.me

# default banner
img: default